compat version with test
r-murphy/openui5-preload pull request #4
Opened 2020-05-13 06:49 UTC by CarlosOrozco88

2020-05-15 01:59 UTC, r-murphy commented
Hi @CarlosOrozco88 .
Thanks for the PR. I'll have a look at it soon. But I can't merge as-is with the 2 latest commits removing me as a contributor and changing the package name.

Ryan

2020-05-15 06:14 UTC, CarlosOrozco88 commented
Im so sorry, i thougth the repository was dead and publish de package fork in npm. I will delete it. I am developing a vscode extension and i need to build for newer ui5 versions.
Thanks!

2020-05-19 04:41 UTC, r-murphy requested changes

2020-05-19 04:41 UTC, r-murphy commented on README.md
> +# ui5-preload
@CarlosOrozco88 can you revert the rename in `README.md` and the mention of the fork. Otherwise, looks good to me.

2020-05-19 20:17 UTC, r-murphy approved these changes

2020-05-19 20:17 UTC, r-murphy commented
Looks good. Thanks!

2020-05-19 20:18 UTC, merged

2020-05-19 20:53 UTC, r-murphy commented
@CarlosOrozco88  I just published version 3.0.0 (major bump due to some deps requiring node 10+). Please give it a try and let me know how it goes. 
Also, are you using the CLI or only the imported API? Since you plan to use this in a VS Code extension, I can pull the CLI out into its own module to minimize dependencies for your extension.